{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-grab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GRAB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GRAB/GRAB_{{ version }}.tar.gz
  sha256: edf855665ede1ec4288a6506b09c38393e9c0970ef401b4f33a4f3326d572523

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ stdlib("c") }}            # [not win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-data.table
    - r-dplyr
    - r-igraph
    - r-lme4
    - r-matrix
    - r-mvtnorm
    - r-ordinal
    - r-rsqlite
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel
    - r-survival
    - libblas
    - liblapack
    - zlib
  run:
    - r-base
    - r-data.table
    - r-dplyr
    - r-igraph
    - r-lme4
    - r-matrix
    - r-mvtnorm
    - r-ordinal
    - r-rsqlite
    - r-rcpp
    - r-rcppparallel
    - r-survival

test:
  commands:
    - $R -e "library('GRAB')"           # [not win]
    - "\"%R%\" -e \"library('GRAB')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GRAB
  dev_url: https://github.com/cran/GRAB
  license: GPL-2.0-or-later
  summary: Provides a comprehensive suite of genome-wide association study (GWAS) methods specifically designed for biobank-scale data. The package offers computationally efficient and robust association tests for time-to-event traits (e.g., Bi et al., 2020 <doi:10.1016/j.ajhg.2020.06.003>), ordinal categorical traits (e.g.,
    Bi et al., 2021 <doi:10.1016/j.ajhg.2021.03.019>), and longitudinal traits (Xu et al., 2025 <doi:10.1038/s41467-025-56669-1>). Additionally, it includes functions for simulating genotype and phenotype data to support research and method development.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - WoodyMiao
