{% set version = '0.2.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-grab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GRAB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GRAB/GRAB_{{ version }}.tar.gz
  sha256: 3acd6fcd1ddd6fd3e211b3327995687541851eb4c802ad73741c1fd1bd95b376

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib("c") }}                # [not win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-matrix
    - r-rsqlite
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel
    - r-data.table
    - r-dplyr
    - r-igraph
    - r-lme4
    - r-mvtnorm
    - r-ordinal
    - r-survival
    - zlib
    - libopenblas
  run:
    - r-base
    - r-bh
    - r-matrix
    - r-rsqlite
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel
    - r-data.table
    - r-dplyr
    - r-igraph
    - r-lme4
    - r-mvtnorm
    - r-ordinal
    - r-survival
    - zlib
    - libopenblas
    - r-dbplyr
    - r-optparse
    - r-tidyr
    - r-r.utils
    - r-skat

test:
  commands:
    - $R -e "library('GRAB')"           # [not win]
    - "\"%R%\" -e \"library('GRAB')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GRAB
  license: GPL-2.0-or-later
  summary: Provides a comprehensive suite of genome-wide association study (GWAS) methods specifically
    designed for biobank-scale data. The package offers computationally efficient and
    robust association tests for time-to-event traits (e.g., Bi et al., 2020 <doi:10.1016/j.ajhg.2020.06.003>),
    ordinal categorical traits (e.g., Bi et al., 2021 <doi:10.1016/j.ajhg.2021.03.019>),
    and longitudinal traits (Xu et al., 2025 <doi:10.1038/s41467-025-56669-1>). Additionally,
    it includes functions for simulating genotype and phenotype data to support research
    and method development.
  license_family: GPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - WoodyMiao

# Package: GRAB
# Type: Package
# Title: Genome-Wide Robust Analysis for Biobank Data (GRAB)
# Version: 0.2.2
# Date: 2025-08-01
# Authors@R: c(person(given = "Wenjian", family = "Bi", role = "aut"), person(given = "Wei", family = "Zhou", role = "aut"), person(given = "Rounak", family = "Dey", role = "aut"), person(given = "Zhangchen", family = "Zhao", role = "aut"), person(given = "Seunggeun", family = "Lee", role = "aut"), person(given = "Woody", family = "Miao", role = "cre", email = "miaolin@pku.edu.cn"))
# Description: Provides a comprehensive suite of genome-wide association study (GWAS) methods specifically designed for biobank-scale data. The package offers computationally efficient and robust association tests for time-to-event traits (e.g., Bi et al., 2020 <doi:10.1016/j.ajhg.2020.06.003>), ordinal categorical traits (e.g., Bi et al., 2021 <doi:10.1016/j.ajhg.2021.03.019>), and longitudinal traits (Xu et al., 2025 <doi:10.1038/s41467-025-56669-1>). Additionally, it includes functions for simulating genotype and phenotype data to support research and method development.
# License: GPL (>= 2)
# Encoding: UTF-8
# Depends: R (>= 3.5.0)
# Imports: dplyr, data.table, mvtnorm, Matrix, RSQLite, lme4, ordinal, survival, Rcpp, RcppParallel, igraph
# Suggests: dbplyr, optparse, tidyr, R.utils, SKAT
# LinkingTo: Rcpp, RcppArmadillo, RcppParallel, BH
# RoxygenNote: 7.3.2
# NeedsCompilation: yes
# Packaged: 2025-07-29 07:41:10 UTC; Woody
# Author: Wenjian Bi [aut], Wei Zhou [aut], Rounak Dey [aut], Zhangchen Zhao [aut], Seunggeun Lee [aut], Woody Miao [cre]
# Maintainer: Woody Miao <miaolin@pku.edu.cn>
# Repository: CRAN
# Date/Publication: 2025-07-29 09:20:38 UTC
